### ISSUE TITLE
Error no matches for kind "Application" in version "app.k8s.io/v1"

### ISSUE THREAD

**Issue by isavcic** [e2fyi/kubeflow-aws#10]
When applying (excerpt below):
```yaml
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    iam.amazonaws.com/role: kube2iam-role
  name: pipeline
  namespace: kubeflow
```
Using:
```
kubectl kustomize overlay/iam
```
